In [24]:



# import numpy as np


# X = np.array([[0,0],
#               [0,1],
#               [1,0],
#               [1,1]])

# Y = np.array([[0],
#               # [1]
#               [1],
#               [0]])

# print("XOR Inputs:\n", X)
# print("XOR Outputs:\n", Y)




XOR Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
XOR Outputs:
 [[0]
 [1]
 [1]
 [0]]


In [25]:
# # Initialize parameters
# # nn of input size 2, hidden layers -2 and output size 1
# np.random.seed(42)
# input_size = 2
# hidden_size = 4
# output_size = 1

# W1 = np.random.randn(input_size, hidden_size)
# b1 = np.zeros((1, hidden_size))

# W2 = np.random.randn(hidden_size, output_size)
# b2 = np.zeros((1, output_size))
# W1 = np.random.randn(input_size, hidden_size)
# b1 = np.zeros((1, hidden_size))

# W2 = np.random.randn(hidden_size, output_size)
# b2 = np.zeros((1, output_size))


In [26]:
# # training 
# def relu(Z):
#     return np.maximum(0, Z)

# def relu_derivative(Z):
#     return (Z > 0).astype(float)

# def sigmoid(Z):
#     return 1 / (1 + np.exp(-Z))



# learning_rate = 0.1
# epochs = 5000




# for epoch in range(epochs):
    
#     # Forward pass
#     Z1 = X.dot(W1) + b1
#     A1 = relu(Z1)
    
#     Z2 = A1.dot(W2) + b2
#     A2 = sigmoid(Z2)
    
#     # Loss
#     loss = -np.mean(Y*np.log(A2+1e-8) + (1-Y)*np.log(1-A2+1e-8))

In [27]:


    
    # Backpropagation


hello


In [11]:



import numpy as np


X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])

print("XOR Inputs:\n", X)
print("XOR Outputs:\n", Y)



np.random.seed(42)
input_size = 2
hidden_size = 4
output_size = 1

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))




def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return (Z > 0).astype(float)

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))




learning_rate = 0.1
epochs = 5000




for epoch in range(epochs):
    

    Z1 = X.dot(W1) + b1
    A1 = relu(Z1)
    
    Z2 = A1.dot(W2) + b2
    A2 = sigmoid(Z2)
    
   
    loss = -np.mean(Y*np.log(A2+1e-8) + (1-Y)*np.log(1-A2+1e-8))
    
 
    dZ2 = A2 - Y
    dW2 = A1.T.dot(dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)
    
    dA1 = dZ2.dot(W2.T)
    dZ1 = dA1 * relu_derivative(Z1)
    dW1 = X.T.dot(dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)
    
    
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")




print("\nFinal Predictions:")
pred = (A2 > 0.5).astype(int)
print(pred)




print("\nHidden Layer Activations (A1):")
print(A1)
print("\nOutput Layer (A2):")
print(pred)


XOR Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
XOR Outputs:
 [[0]
 [1]
 [1]
 [0]]
Epoch 0, Loss: 0.9179
Epoch 1000, Loss: 0.0066
Epoch 2000, Loss: 0.0027
Epoch 3000, Loss: 0.0017
Epoch 4000, Loss: 0.0012

Final Predictions:
[[0]
 [1]
 [1]
 [0]]

Hidden Layer Activations (A1):
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.38471400e-05 0.00000000e+00 2.81154531e-04 3.23176831e+00]
 [1.92673204e-05 0.00000000e+00 2.30592562e-04 3.23173672e+00]
 [2.55407271e+00 0.00000000e+00 3.35414162e+00 6.46366471e+00]]

Output Layer (A2):
[[0]
 [1]
 [1]
 [0]]


In [7]:
for i in range(A1.shape[1]):
    print(f"Neuron {i+1} output:", A1[:, i])

Neuron 1 output: [0.00000000e+00 3.38471400e-05 1.92673204e-05 2.55407271e+00]
Neuron 2 output: [0. 0. 0. 0.]
Neuron 3 output: [0.00000000e+00 2.81154531e-04 2.30592562e-04 3.35414162e+00]
Neuron 4 output: [0.         3.23176831 3.23173672 6.46366471]


In [8]:
print("Z1:", Z1)
print("A1:", A1)
print("dW1:", dW1)
print("Shapes:", Z1.shape, A1.shape, dW1.shape)

Z1: [[-2.55401959e+00  0.00000000e+00 -3.35362987e+00 -1.59687594e-04]
 [ 3.38471400e-05 -2.34136957e-01  2.81154531e-04  3.23176831e+00]
 [ 1.92673204e-05 -1.38264301e-01  2.30592562e-04  3.23173672e+00]
 [ 2.55407271e+00 -3.72401258e-01  3.35414162e+00  6.46366471e+00]]
A1: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.38471400e-05 0.00000000e+00 2.81154531e-04 3.23176831e+00]
 [1.92673204e-05 0.00000000e+00 2.30592562e-04 3.23173672e+00]
 [2.55407271e+00 0.00000000e+00 3.35414162e+00 6.46366471e+00]]
dW1: [[ 0.00052029  0.          0.00065872 -0.00050552]
 [ 0.00052065  0.          0.00065918 -0.00050587]]
Shapes: (4, 4) (4, 4) (2, 4)


In [9]:


# Gradient of output w.r.t input
dA2_dZ2 = A2 * (1 - A2)  # sigmoid derivative
dZ2_dA1 = W2               # derivative of Z2 w.r.t A1
dA1_dZ1 = relu_derivative(Z1)
dZ1_dX = W1                 # derivative of Z1 w.r.t X

# Chain rule: dA2/dX = dA2/dZ2 * dZ2/dA1 * dA1/dZ1 * dZ1/dX
input_contributions = dA2_dZ2.dot(dZ2_dA1.T) * dA1_dZ1
input_contributions = input_contributions.dot(dZ1_dX.T)

print("\nFeature Contributions (how much each input affects output):")
for i, xi in enumerate(X):
    print(f"Input {xi} -> Contribution: {input_contributions[i]}")


Feature Contributions (how much each input affects output):
Input [0 0] -> Contribution: [0. 0.]
Input [0 1] -> Contribution: [-0.00632076 -0.00632085]
Input [1 0] -> Contribution: [-0.00631944 -0.00631952]
Input [1 1] -> Contribution: [-0.00441646 -0.00441652]


In [12]:
from sklearn.datasets import fetch_openml
import numpy as np

In [ ]:
mnist = fetch_openml('mnist_784', version=1)

X = mnist.data.values[:500] / 255.0   # normalize
y = mnist.target.astype(int).values[:500]

In [ ]:
def one_hot(y, num_classes=10):
    oh = np.zeros((len(y), num_classes))
    oh[np.arange(len(y)), y] = 1
    return oh

y_onehot = one_hot(y)